### ISSUE TITLE
Example doesn't work?

### ISSUE THREAD

**Issue by yongxiu** [liztio/cluster-api-provider-mailgun#1]
This example doesn't seem to work, I followed [instruction](https://github.com/kubernetes-sigs/cluster-api/tree/master/docs/book/src/developer/providers/implementers-guide), and met error in capi-system\capi-controller-manager-6d7b58b889-5mbfg pod:

`
E0509 03:06:56.435811       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to find a CustomResourceDefinition for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=MailgunCluster with contract \"cluster.x-k8s.io/v1alpha3\""  "controller"="cluster" "request"={"Namespace":"default","Name":"hello-mailgun"}
`

And in pod cluster-api-provider-mailgun-system\cluster-api-provider-mailgun-controller-manager-79c644b8975dnzc , the error is:
`
ERROR   controller-runtime.controller   Reconciler error        {"controller": "mailguncluster", "request": "default/hello-mailgun", "error": "failed to retrieve cluster: {Name:hello-mailgun GenerateName: Namespace:default SelfLink:/apis/infrastructure.cluster.x-k8s.io/v1alpha3/namespaces/default/mailgunclusters/hello-mailgun UID:e5684416-9d10-47ec-84fe-b96a236f2dde ResourceVersion:116159 Generation:1 CreationTimestamp:2020-05-09 00:31:45 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"infrastructure.cluster.x-k8s.io/v1alpha3\",\"kind\":\"MailgunCluster\",\"metadata\":{\"annotations\":{},\"name\":\"hello-mailgun\",\"namespace\":\"default\"},\"spec\":{\"priority\":\"ExtremelyUrgent\",\"request\":\"Please make me a cluster, with sugar on top?\",\"requester\":\"cluster-admin@example.com\"}}\n] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName: ManagedFields:[{Manager:kubectl Operation:Update APIVersion:infrastructure.cluster.x-k8s.io/v1alpha3 Time:2020-05-09 00:31:45 +0000 UTC Fields:nil}]}"}
`

The cluster yaml file is the example

```
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: hello-mailgun
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MailgunCluster
    name: hello-mailgun
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MailgunCluster
metadata:
  name: hello-mailgun
spec:
  priority: "ExtremelyUrgent"
  request: "Please make me a cluster, with sugar on top?"
  requester: "cluster-admin@example.com"
```

Am I missing anything?
